# Isaac Lab 2.2 task skeleton for GO2
name: go2_warehouse_task
physics_hz: 120
control_hz: 30

env:
  max_episode_length: 500
  reset:
    pos_range: [ -1.0, 1.0 ]
    yaw_range: [ -3.14, 3.14 ]

observations:
  state:
    - base_lin_vel
    - base_ang_vel
    - base_height
    - imu_quat

actions:
  scale:
    lin_xy: 0.5
    yaw: 0.8

rewards:
  placeholders:
    - survive_bonus
    - forward_progress
    - smoothness
